import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

// export const getStaticProps = async () => {
//   const res = await fetch("/api/userRegister/getUser");
//   const data = await res.json();
//   return {
//     props: {
//       posts: data,
//     },
//   };
// };

export default function Home() {
  const [users, setUsers] = useState([]);


  const fetchUser = async () => {
    let { data } = await axios.get("http://localhost:3000/api/userRegister/getImages");
    setUsers(data);
  };



  useEffect(() => {
    fetchUser();
  }, []);

  let img = users.filter((e) => {
    return e.imgCollection.length > 0
     
  });

  console.log("img:", img);
  return (
    <>
      <Head>
        <title>DIGITAL FORCE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/digital_force_round.png" />
      </Head>
      <main>
        {/* Navbar */}
        <Navbar />

        {/* Home Page */}
        <h2 className={styles.heading}>All Collections</h2>

        {/* <div className={styles.container}>
          {img.map((item) => (
            <div className={styles.image_container} key={item._id}>
              <img className={styles.images} src={item.image} alt={item.name} />
              <p className={styles.names}>{item.name}</p>
            </div>
          ))}
        </div> */}

        {/* Footer */}
        <Footer />
      </main>
    </>
  );
}
