import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export const getStaticProps = async () => {
  const res = await fetch(
    "https://repulsive-nightgown-colt.cyclic.app/products?category=skin"
  );
  const data = await res.json();
  return {
    props: {
      posts: data,
    },
  };
};

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>DIGITAL FORCE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/digital_force_round.png" />
      </Head>
      <main>
        {/* Navbar */}
        <Navbar />

        {/* Home Page */}
        <h2 className={styles.heading}>All Collections</h2>

        <div className={styles.container}>
          {posts.map((item) => (
            <div className={styles.image_container} key={item._id}>
              <img className={styles.images} src={item.image} alt={item.name} />
              <p className={styles.names}>{item.name}</p>
            </div>
          ))}
        </div>

        {/* Footer */}
        <Footer />
      </main>
    </>
  );
}
